### ISSUE TITLE
拖拽之后可以生成html吗

### ISSUE THREAD

**Issue by springAppl** [chinanf-boy/react-beautiful-dnd-zh#1]
拖拽之后可以生成html吗，我想要做个装修系统，希望托转完毕之后可以生成html导出

**Comment by chinanf-boy** [comment]
这个问题，应该是 库应用本身的

去，维护项目提 issue 比较合适
https://github.com/atlassian/react-beautiful-dnd

这个库，主要功能在于拖拽

不过，所谓的 html导出，可以试试使用生命周期onDragEnd 获取拖动的所有信息，然后自己维护一个 存储

> 希望有用
